project:
  type: book
  output-dir: docs

navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Preface"
        href: preface.qmd
book:
  title: "AI-839"
  subtitle: "ML Production Engineering"
  reader-mode: true

  page-footer:
    left: |
      course under prep.
    right: |
      This course material was built with <a href="https://quarto.org/">Quarto</a> with <a href="https://github.com/hadley/r4ds">r4ds</a> theme.
  
  cover-image: crisp-ml-process.jpg
  favicon: crisp-ml-process.jpg
  site-url: https://mlsquare.github.io/ai-839
  repo-url: https://github.com/mlsquare/ai-839
  repo-branch: main
  repo-actions: [edit, issue]
  
  chapters:
  - preface.qmd
  - index.qmd
  - course.qmd        
  - part: Lectures[ML Engg.]
    chapters:
    - ./lectures/w01-l01.qmd
    - ./lectures/w02-l01.qmd
    - ./lectures/w02-l02.qmd
    - ./lectures/w03-l01.qmd
    - ./lectures/w03-l02.qmd
    - ./lectures/w04-l01.qmd
    - ./lectures/w04-l02.qmd
    - ./lectures/w05-l01.qmd
    - ./lectures/w05-l02.qmd
    - ./lectures/w06-l01.qmd
    - ./lectures/w06-l02.qmd
  - part: Lectures[ML Science]
    chapters:
    - ./lectures/w07-l01.qmd
    - ./lectures/w07-l02.qmd
    - ./lectures/w08-l01.qmd
    - ./lectures/w09-l01.qmd
    - ./lectures/w11-l02.qmd
  - part: LLMs-Ops
    chapters:
    - ./lectures/w13-l01.qmd
    - ./lectures/w13-l02.qmd
    - ./lectures/w13-l03.qmd
  - part: Lectures[ML Science]
    chapters:
    - ./lectures/w15-l01.qmd
    - ./lectures/w16-l01.qmd
    - ./lectures/w16-l02.qmd
  
  - homeworks.qmd
  - projects.qmd
  - tutorials.qmd
  - talks.qmd
  - part: Notebooks
    chapters:
    - ./notebooks/Sample-Hardness.ipynb
    - ./notebooks/Sample-Fitness.ipynb
    - ./notebooks/Conformal-Predictions.ipynb
  - part: documentation.qmd 
    chapters:
    - ./resources/project-card.ipynb
  
  
format:
  html:
    theme:
    - pulse
    - mlops.scss
    code-link: true
    author-meta: "mlsquare"
    callout-appearance: simple
    number-sections: false
editor: visual

