---
title: "Course"
bibliography: references.bib
csl: ieee.csl
link-citations: true

---

You will find below course syllabus and schedule for _AI-839: ML Production Engineering_ course offered at [IIIT-B](https://www.iiitb.ac.in/) in the Fall of 2024. This will evolve as the course progress.


### Syllabus & Schedule

::: {style="font-size: 80%;"}

| Wk | Dt | Topics | Resources |
| :- | :- | :------- | :------- |
| 01 | 01-Aug | **Introduction** <br> 1. Course Intro <br> 2. ML in Production - Intro <br> | [W01-L01](./lectures/w01-l01.qmd) |
&nbsp; | | @sec-hw-01 |  Due Tue, 13th, August, 2024, 11.59pm IST |
| 02 | 06-Aug <br> 09-Aug | **Discovery** <br> 1. Contd.  _ML in Production - Intro_ <br> 2. Software 1.0 vs 2.0 <br> 3. Design Thinking, Project Cards <br> 4. MLOps Canvas & Tool Landscape | [W02-L01](./lectures/w02-l01.qmd) <br> [W02-L02](./lectures/w02-l02.qmd)  |
&nbsp; |   | @sec-hw-02 | Due Fri, 23rd, August, 2024, 11.59pm IST  |
| 03 | 13-Aug <br> 16-Aug | **Models for Modeling** <br> 1. Kedro   <br>  2. DevOps  | [W03-L01](./lectures/w03-l01.qmd) <br>  [W03-L02](./lectures/w03-l02.qmd) |
&nbsp; | Note:| 16-Aug | DevOps guest lecture by [Ravi](https://www.linkedin.com/in/ravismula/)   |
| 04 | 20-Aug <br> 23-Aug | **Dev Setup & Data Monitoring** <br> 1. Kedro, PyTest, Ruff, Quartodoc   <br>  2. Data Quality  | [W04-L01](./lectures/w04-l01.qmd) <br> [W04-L02](./lectures/w04-l02.qmd) |
&nbsp; | | @sec-hw-03 <br> @sec-hw-04 |  11.59PM IST, Friday, 6th Sep, 2024. <br> 11.59PM IST, Friday, 16th Sep, 2024.     |
| 05 | 27-Aug <br> 30-Aug | **Model Monitoring and Deployment** <br> 1. Monitoring Metrics, Tests, Label Generation    <br>  2. Deployment with MLFlow  | [W05-L01](./lectures/w05-l01.qmd) <br> [W05-L02](./lectures/w05-l02.qmd) |
&nbsp; | |  |     |
| 06 | 03-Sep <br> 06-Sep | **Evaluation and Governance** <br> 1. Hypothesis Tets, DoEs, Model Comparison   <br>  2. The R4 Framework | [W06-L01](./lectures/w06-l01.qmd) <br> [W06-L02](./lectures/w06-l02.qmd) |
&nbsp; |  | @sec-hw-05 <br> @sec-hw-06 | Due 11.59PM IST, Tuesday, 24th Sep, 2024  <br> Due 11.59PM IST, Friday, 18th Oct, 2024 |
: **Part-1: Essentials** {.striped}
:::



::: {style="font-size: 80%;"}
| Wk | Dt | Topics | Resources |
| :- | :- | :------- | :------- |
| 07 | 10-Sep <br> 13-Sep | **Scaling Laws, Sample Hardness** <br> 1. Sample Sizes, Active Learning, Scaling Laws <br> 2. Sample Hardness | [W07-L01](./lectures/w07-l01.qmd) <br> [W07-L02](./lectures/w07-l02.qmd) |
&nbsp; |  |   @sec-hw-minor | Due 11.59PM IST, Friday, 25th Oct, 2024 |
| 08 | 17-Sep <br> 20-Sep | **Sample Fitness, Guest Lecture** <br> 1. Likelihood Ratio, $\nu\text{-information}$ <br> 2. ML Platform | [W08-L01](./lectures/w08-l01.qmd) <br> Talk by Abhishek |
&nbsp; |  |    |  |
| 09 | 24-Sep <br> 27-Sep | **UQ, Midterm** <br> 1. Uncertainty Quantification, Conformal prediction <br> 2. Midterm | [W09-L01](./lectures/w09-l01.qmd) <br> NA |
&nbsp; |  |   Midterm | in-class |
| 10 | 15-Oct <br> 18-Oct | **Edge Deployment, ML Platforms** <br> 1. Model Compression, Quantization   <br> 2. Distributed Systems, Solving ML Eng. issues with Keras and TensorFlow | [Talk](./talks/EdgeDeployment_SrinivasRana.pdf) by Dr. Srinivas <br> [Talk](./talks/MLOps_Kalyan.pdf) by Kalyan |
&nbsp; |  |    |  |
| 11 | 22-Oct <br> 25-Oct | **Causal ML, Robustness** <br> 1. DoWhy and DICE   <br> 2. Gradients is all you need | [Talk](./talks/CausalML_dowhy_dice_Amit.pdf) by Dr. Amit <br> [W11-L02](./lectures/w11-l02.qmd)  |
&nbsp; |  |    |  |
| 12 | 29-Oct <br> 01-Nov | **Robustness** <br> 1. Securing ML  <br> 2. Holiday | Talk by Manoj Parmar <br> NA |
&nbsp; |  |    |  |
| 13 | 05-Nov <br> 08-Nov | **LLMOps** <br> 1. LLMs & MLOps Intro  <br> 2. Building LLM Apps in Fintech | Lecture <br> Talk by Dr. Venkata |
&nbsp; |  |    |  |
| 14 | 12-Nov <br> 15-Nov | **Fairness, XAI** <br> 1. Bias and Privacy  <br> 2. XAI in different modalities  | TBD <br> TBD |
&nbsp; |  |    |  |
| 15 | 19-Nov <br> 22-Nov | **Security, Machine Unlearning** <br> 1. ML Vulnerabilities and Safeguards  <br> 2. Recent work on model unlearning | Talk by Puneet Jindal <br> TBD |
&nbsp; |  |    |  |
| 16 | Last Week | **Student Presentations**  | TBD |
&nbsp; | 26-Nov <br> 29-Nov |  in-class final presentations  |  |

: **Part-2: Full Stack ML** {.striped}
:::


::: {style="font-size: 80%;"}
| Wk | Dt | Topics | Resources |
| :- | :- | :------- | :------- |
| 03 | 16-Aug |  Intro to DevOps <br> [ML Engineering]  | [Ravi Mula](https://www.linkedin.com/in/ravismula/) <br> Architect: [Sanketika](https://sanketika.in/) |
| 08 | 20-Sep |  ML Platforms <br> [ML Engineering]  | [Abhishek Choudhary](https://www.linkedin.com/in/abhishekch123/) <br> Co-Founder & CTO: [TrueFoundry](https://www.truefoundry.com/) |
| 10 | 15-Oct |  Deploying on Edges <br> [ML Engineering] <br> [Deck](./talks/EdgeDeployment_SrinivasRana.pdf) | [Dr. Srinivas Rana](https://www.linkedin.com/in/srinivasrana/) <br> Sr ML Scientist: [Wadhwani AI](https://www.wadhwaniai.org/) |
| 10 | 18-Oct |  MLOps @ Scale <br> [ML Engineering] <br> [Deck](./talks/MLOps_Kalyan.pdf)  | [Kalyan Deepak](https://www.linkedin.com/in/kalyan-deepak-2304622a/) <br> Sr Staff Engineer, [LinkedIn](https://www.linkedin.com/)  |
| 11 | 22-Oct |   DoWhy, DiCE  <br> [Causal ML] <br> [Deck](./talks/CausalML_dowhy_dice_Amit.pdf) | [Dr. Amit Sharma](https://www.amitsharma.in/) <br> Principal Researcher, [MSR](https://www.microsoft.com/en-us/research/lab/microsoft-research-india/) |
| 12 | 29-Oct |   Securing AI  <br> [Adversarial ML]  | [Manojkumar Parmar](https://www.linkedin.com/in/manojkumarparmar/) <br> CEO & CTO AI Shield [Bosch AI Shield](https://www.linkedin.com/company/bosch-aishield/) |
| 13 | 08-Nov | Building LLMs in Production in Regulated Industry <br> [System Design] | [Dr. Venkata Pingali](https://www.linkedin.com/in/pingali/) <br> Co-Founder: [Scribble Data](https://www.scribbledata.io/) |
| 14 | 15-Nov | Problems and Solutions in Data Labelling <br> [Data Collection] | [Puneet Jindal](https://www.linkedin.com/in/puneetjindalisb/) <br> CEO, [Labellerr](https://www.linkedin.com/company/labellerr/)
: **Guest Lectures** {.striped}
:::



## Discussions
We will use WhatsApp group for (informal)discussions and alerts.


## References
1. \[book\] [ML Engineering](https://www.mlebook.com/wiki/doku.php), Andiry Burkov, 2019, LeanPub
2. \[book\] [Effective Data Science Infrastructure](https://www.manning.com/books/effective-data-science-infrastructure), Vile Tuulos, 2023, Manning
3. \[book\] [ML System Design](https://www.oreilly.com/library/view/designing-machine-learning/9781098107956/), Chip Huyen, 2023, O'Reilly
4. \[course\] [CS329S @ Stanford:  ML Systems Design](https://stanford-cs329s.github.io/), Chip Huyen, 2022
5. \[course\] [MLOps](https://github.com/GokuMohandas/mlops-course), Chip Huyen, 2024



## Grading

- 40%: Six assignments
- 15%: Midterm mini project
- 20%: In-class midterm
- 25%: Capstone project


## Policies

- _Late Submissions_: \ All deadlines are due at on the date and time indicated on the course page. The penalties for late submission
are as follows:
    - Late submissions not allowed (incur a zero) - except with prior approval or in valid exceptional cases

- _Make-up Exam/Submission Policy_: As per institute [policy](https://www.iiitb.ac.in/includefiles/userfiles/images/pdf/code-of-coduct.pdf)
- _Citation Policy for Papers_: Always mention the source, give full attribution and credits to citations, and as per institute [policy](https://www.iiitb.ac.in/includefiles/userfiles/images/pdf/code-of-coduct.pdf)
- _Academic Dishonesty/Plagiarism_: As per institute [policy](https://www.iiitb.ac.in/includefiles/userfiles/images/pdf/code-of-coduct.pdf)
- _Accommodation of Divyangs_: As per institute [policy](https://www.iiitb.ac.in/includefiles/userfiles/images/pdf/code-of-coduct.pdf)



[Soma S Dhavala](https://www.linkedin.com/in/somasdhavala/) \
Course Instructor