# Welcome {.unnumbered}


Hello Students of AI 839.

See the [course](./course.qmd) page for recent information on Lectures, Homeworks, Projects, etc.. 

## Announcements  
- [30-November-2024] COURSE ENDS
- [30-November-2024] Project Presentations
- [29-November-2024] Project Presentations
- [26-November-2024] Machine Unlearning [W16-L02](/lectures/w16-l02.qmd)  added to course page
- [26-November-2024] Fairness and Bias [W16-L01](/lectures/w16-l01.qmd)  added to course page
- [19-November-2024] Meta Learning lecture page [W15-L01](/lectures/w15-l01.qmd)  added to course page
- [15-November-2024] Data Labelling guest lecture deck added to course page
- [13-November-2024] AI Security guest lecture deck added to course page
- [07-November-2024] Lecture page added to [W13-L01](/lectures/w13-l01.qmd), [W13-L02](/lectures/w13-l02.qmd)
- [25-October-2024] Lecture page added to [W11-L02](/lectures/w11-l02.qmd)
- [22-October-2024] Dr. Amit's Causal ML deck added to course page.
- [22-October-2024] Guest lecture decks added.
- [01-October-2024] Generic feedback on HWs is added to [homeworks](./homeworks.qmd) page.
- [30-September-2024] @sec-hw-midterm-bonus released. Due by 11.59pm, Oct 15, 2024 IST.
- [27-September-2024] Midterm at 11.15am, Tue, Sept, 2024 IST. 
- [17-September-2024] @sec-hw-05 extended to 11.59pm, Tue, Sept, 2024 IST.
- [16-September-2024] Notes added to [W08-L01](/lectures/w08-l01.qmd). Updated course page with scheudle for the rest of the course (tentative).
- [12-September-2024] Notes added to [W07-L01](/lectures/w07-l01.qmd). [W07-L02](/lectures/w07-l02.qmd) is added.
- [05-September-2024] Homework, Minor and Major preoject details added. See @sec-hw-05, @sec-hw-06, @sec-hw-minor, @sec-hw-major for details.  Course pages updated.
- [05-September-2024] Lecture Page [W05-L01](/lectures/w05-l01.qmd), [W05-L02](/lectures/w05-l02.qmd), [W06-L01](/lectures/w06-l01.qmd), [W06-L02](/lectures/w06-l02.qmd) added. Course pages updated.
- [25-August-2024] Lecture Page [W03-L02](/lectures/w03-l02.qmd), [W04-L01](/lectures/w04-l01.qmd), [W04-L02](/lectures/w04-l02.qmd)  added. Course pages updated.
- [23-August-2024] @sec-hw-03 and @sec-hw-04 added.
- [13-August-2024] Lecture Page [W03-L01](/lectures/w03-l01.qmd) added. Course pages updated.
- [09-August-2024] Lecture Page [W02-L02](/lectures/w02-l02.qmd) added. Course pages updated. @sec-hw-02 added
- [06-August-2024] Lecture Page [W02-L01](/lectures/w02-l01.qmd) added. [Project Card](./resources/project-card.ipynb), as a jupyter notebook is added.
- [01-August-2024] Course website up, Lecture Page [W01-L01](/lectures/w01-l01.qmd) added. @sec-hw-01 added.


## Overview

**Prereqs**

- Exposure and skill in data handling, building models in Python, PyTorch
- Exposure and skill in developing code using Python, Git, IDEs like VS Code
- A foundation course in Machine Learning, Deep Learning, Data Modeling, working with (Big) Data


**Part-1: Essentials**

- Topics
    - basic principles and MLOps with Open Source Software
    - three assignments
- Learning Outcomes: students will be able to
    - deploy models with logging, documentation, unit tests, and APIs
    - understand a conceptual framework to approach MLOps holistically 

**Part-2: Full Stack MLOps**

- Topics
    - holistic understanding of ML development, beyond chasing typical performance metrics
    - one assignment, one mini project and a midterm
- Learning Outcomes: students will be able to
    - deploy models, observe their performance, make improvements, redeploy them.  
    - ensure that the ML pipeline is reproducible. 
    - incorporate principles from Responsible AI and build ML systems which can consist of many models and tools.    

**Part-3: Intro to LLM(Ops) & Application**

- Topics
    - practice, cloud solutions
    - capstone project and presentations
    - invited lectures from Industry
- Learning Outcomes: students will be able to
    - frame, discover, develop, deploy, monitor, improve, re-deploy and maintain an ML Application
    - approach the problem holistically, optimize RoI




